### ISSUE TITLE
Some types get parsed to typing.Any

### ISSUE THREAD

**Issue by m-alek** [lexiq-legal/pydantic_schemaorg#2]
**Description**
Each schema.org object has expected types for its properties.

**Problem**
It seems not all expected types get parsed properly. E.g. <https://schema.org/Person>, or <https://schema.org/Place get parsed to type 'typing.Any'

e.g. the property <https://schema.org/maintainer> of <https://schema.org/CreativeWork> should allow both Organization and Person, however it got parsed to Organization and typing.Any (see <https://github.com/lexiq-legal/pydantic_schemaorg/blob/main/pydantic_schemaorg/CreativeWork.py#L74>)

**Comment by crbaker89** [comment]
Thanks for the bug report, should be fixed now!
